@startuml

hide circle
skinparam linetype ortho

entity User {
    * user_id : INT <<PK>>
    --
    username : VARCHAR
    email : VARCHAR
    password_hash : VARCHAR
}

entity Folder {
    * folder_id : INT <<PK>>
    --
    folder_name : VARCHAR
    parent_folder_id : INT <<FK>>
    user_id : INT <<FK>>
}

entity File {
    * file_id : INT <<PK>>
    --
    file_name : VARCHAR
    file_size : INT
    file_type : VARCHAR
    folder_id : INT <<FK>>
    user_id : INT <<FK>>
}

entity FileShare {
    * file_id : INT <<PK, FK>>
    * to_user_id : INT <<PK, FK>>
    --
    permission : ENUM
}

entity FolderShare {
    * folder_id : INT <<PK, FK>>
    * to_user_id : INT <<PK, FK>>
    --
    permission : ENUM
}


' Main relationships

User ||--o{ Folder : owns

User ||--o{ File : owns

Folder ||--o{ File : contains

Folder ||--o{ Folder : parent


' Sharing relationships

File ||--o{ FileShare : shared

User ||--o{ FileShare : receives

Folder ||--o{ FolderShare : shared

User ||--o{ FolderShare : receives


@enduml
